name: Build and Push Docker Image

on:
  push:
      tags:
        -'*'

jobs:
  build_and_push: 
    runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: action/checkout@v4

  - name: Setup Docker Buildx
    uses: docker/setup-buildx-action@v3